### ISSUE TITLE
Need update to support EarthMC Dynmap!!!

### ISSUE THREAD

**Issue by StarDustShine** [32Vache/emc-mapmodes#4]
**Describe the bug**
Cannot load a json in website, staying on "Processing data".

**To Reproduce**
When I try to open the website, it shows Procssing Data, and it stayed on this notification for a long time, so i pressed F12 to see errors, it report `Uncaught (in promise) TypeError: Cannot read properties of null (reading '2')
    at main.js:157:20`

**Screenshots**
[![5212.png](https://i.postimg.cc/brCVpf9t/5212.png)](https://postimg.cc/m19yyqqL)

**Info:**
 - Userscript version: 2.5.0
 - Browser: edge
 - OS: windows

**Additional context**
Hmmm.... maybe EarthMC updated their dynmap software?

**Comment by 32Vache** [comment]
Known issue, there is a glitch town on the map causing the app to crash. 

![Screenshot_2023-08-05-22-22-04-407_com.opera.gx.jpg](https://github.com/32Vache/emc-mapmodes/assets/42336759/087c8627-5030-46c2-856d-101f5b53f665)


Thankfully its owner has 42 dayed and the town should be purged soon, that should make the app work again

**Comment by 32Vache** [comment]
Looks like there was several other bug towns. Was in vacation so I could not fix it before but now everything works again
